# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 607fbe769383b06fe2a0edb2c2bb3ed825eb7181b722b50ee6f3d952db5ce6709d9a4c69e45865a65db959914392bc2534eb3736ed67fa8199af165e14e4df16

test:
  secret_key_base: 2e4b43e97e1a5a863c34c22fe58270f9713a8f5e7528ac312ee3e2821de5085f9bdbc74afa333c342626c2657bb720c9db028e26ce40883e070eb2d832a8f737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
